### ISSUE TITLE
想确认一下极客学院上的课程是你录的吗？

### ISSUE THREAD

**Issue by venicehsu** [yorkie/ama#10]
你就是在极客学院上录制了4门课程的yorkie吗？
分别是
1.Node.js 错误处理
2.使用 Node.js 开发命令行工具
3.Node.js 实战项目开发：极客学院“技术问答”
4.使用 loopback 快速搭建用户系统

**Comment by yorkie** [comment]
嗯，以前缺钱的时候录的～

**Comment by venicehsu** [comment]
1.你有微信公众号吗？
2.尤小右的推特上说：Be careful with const/let in if branches when using Babel: they turn the branch into IIFE and can lead to de-opt in perf-critical scenarios.
这里的 perf-critical 应该是 performance-critical 性能关键的意思，
这里的 de-opt 目前搜到的最可能的结果是 de-optionalize,实在不能和某个中文术语对应起来，望点拨。

**Comment by yorkie** [comment]
> 1.你有微信公众号吗？

搜"yorkie_ninja"就可以了

> 2.尤小右的推特上说：Be careful with const/let in if branches when using Babel: they turn the 
> branch into IIFE and can lead to de-opt in perf-critical scenarios.
> 这里的 perf-critical 应该是 performance-critical 性能关键的意思，
> 这里的 de-opt 目前搜到的最可能的结果是 de-optionalize,实在不能和某个中文术语对应起来，望点拨。

直接问本人比较好，帮你 cc @yyx990803
