### ISSUE TITLE
如何阅读express代码呢？

### ISSUE THREAD

**Issue by JosephShing** [yorkie/ama#12]
亲 看到你知乎上回答提到了自己阅读了express源码并写了个lite版 想请教你在阅读前你做了什么准备 对js的理解程度如何 然后阅读时有什么技巧 大概花了多久吗 多谢啦 想了解一下大神的神力啊，=)

**Comment by yorkie** [comment]
https://github.com/weflex/frontend-challenge 可以看看这个，带着问题去读

**Comment by JosephShing** [comment]
好哒 感觉挺有趣的命题 谢谢哈！

**Comment by yorkie** [comment]
https://github.com/weflex/backend-challenge 错了，应该是这个才对。

**Comment by JosephShing** [comment]
好的 谢谢！
