### ISSUE TITLE
- -

### ISSUE THREAD

**Issue by gnipbao** [yorkie/ama#8]
你为什么不写个博客什么的发表自己的文章？

**Comment by yorkie** [comment]
博客的话在这里：https://github.com/yorkie/me/issues 和 http://yorkie.ninja/ 不过也很久没更新了，谢谢关注了。

**Comment by gnipbao** [comment]
嗯;我看过了！不过没看懂你主页上的那副图有什么涵义,还有Sakura是一个博客工具，现在不是有很多博客的框架hexo,wordpress发布很简单呀;我还有一个问题： 你是chinese 现在在上海吗?还是在国外?:trollface:

**Comment by yorkie** [comment]
> 还有Sakura是一个博客工具，现在不是有很多博客的框架hexo,wordpress发布很简单呀

当时我对那些工具不是特别满意吧，自己也想做做

> 你是chinese 现在在上海吗?还是在国外?

国内呀～

**Comment by gnipbao** [comment]
:100:
